# Day 5: NumPy Basics

# Arrays, Indexing, Operations


## 1. Creating Arrays

In [5]:
import numpy as np

In [8]:
# 1D Array
array_1d = np.array([1, 2, 3, 4, 5])
print("1D Array:", array_1d)

1D Array: [1 2 3 4 5]


In [10]:
# 2D Array
array_2d = np.array([[1, 2, 3], [4, 5, 6]])
print("2D Array:\n", array_2d)

2D Array:
 [[1 2 3]
 [4 5 6]]


In [12]:
# Array of Zeros
array_zeros = np.zeros((2, 3))
print("Array of Zeros:\n", array_zeros)

Array of Zeros:
 [[0. 0. 0.]
 [0. 0. 0.]]


In [14]:
# Array of Ones
array_ones = np.ones((3, 2))
print("Array of Ones:\n", array_ones)

Array of Ones:
 [[1. 1.]
 [1. 1.]
 [1. 1.]]


In [16]:
# Range Array
array_range = np.arange(1, 10, 2)
print("Range Array:", array_range)

Range Array: [1 3 5 7 9]


In [19]:
# Linspace Array
array_linspace = np.linspace(0, 1, 5)
print("Linspace Array:", array_linspace)

Linspace Array: [0.   0.25 0.5  0.75 1.  ]


## 2. Indexing and Slicing

In [22]:
# Accessing Elements
print("\nElement at index 2 in 1D Array:", array_1d[2])


Element at index 2 in 1D Array: 3


In [24]:
# Slicing 1D Array
print("Slice of 1D Array (index 1 to 3):", array_1d[1:4])

Slice of 1D Array (index 1 to 3): [2 3 4]


In [26]:
# Accessing Rows and Columns in 2D Array
print("Row 1 of 2D Array:", array_2d[1])
print("Element at Row 1, Column 2 in 2D Array:", array_2d[1, 2])

Row 1 of 2D Array: [4 5 6]
Element at Row 1, Column 2 in 2D Array: 6


## 3. Operations on Arrays

In [29]:
array_a = np.array([10, 20, 30])
array_b = np.array([1, 2, 3])

In [31]:
# Element-wise Operations
print("\nAddition:", array_a + array_b)
print("Subtraction:", array_a - array_b)
print("Multiplication:", array_a * array_b)
print("Division:", array_a / array_b)


Addition: [11 22 33]
Subtraction: [ 9 18 27]
Multiplication: [10 40 90]
Division: [10. 10. 10.]


In [33]:
# Broadcasting
print("Add 5 to Array A:", array_a + 5)

Add 5 to Array A: [15 25 35]


In [35]:
# Universal Functions
print("Square Root of Array A:", np.sqrt(array_a))
print("Exponential of Array B:", np.exp(array_b))

Square Root of Array A: [3.16227766 4.47213595 5.47722558]
Exponential of Array B: [ 2.71828183  7.3890561  20.08553692]


## 4. Aggregations

In [38]:
# Summing Elements
print("\nSum of Array A:", np.sum(array_a))


Sum of Array A: 60


In [40]:
# Mean of Elements
print("Mean of Array B:", np.mean(array_b))

Mean of Array B: 2.0


In [42]:
# Maximum and Minimum
print("Max of Array A:", np.max(array_a))
print("Min of Array A:", np.min(array_a))

Max of Array A: 30
Min of Array A: 10


In [44]:
# Standard Deviation
print("Standard Deviation of Array B:", np.std(array_b))

Standard Deviation of Array B: 0.816496580927726


## 5. Reshaping Arrays

In [47]:
# Reshape 1D Array to 2D
array_reshaped = array_1d.reshape((1, 5))
print("\nReshaped 1D Array to 2D:\n", array_reshaped)


Reshaped 1D Array to 2D:
 [[1 2 3 4 5]]


## 6. Comparisons

In [54]:
#Element-Wise Comparisons
comparison = array_a > 15
print("Elements Greater than 15 in Array A:", comparison)

Elements Greater than 15 in Array A: [False  True  True]
